apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
    - name: ftps
      port: 21
      targetPort: 21
      protocol: TCP
    - name: ftps-data
      port: 30020
      targetPort: 30020
      protocol: TCP
  selector:
    app: ftps
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 30020
          name: ftps-data
        imagePullPolicy: Never
