apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - name: wordpress
      port: 5050
      targetPort: 5050
      protocol: TCP
  selector:
    app: wordpress
    tier: mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: wordpress
        ports:
        - containerPort: 5050
          name: wordpress
        imagePullPolicy: Never
        volumeMounts:
        - name: mysql-data
          mountPath: /var/www/html
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim
